version: nov2023
module: birth_rate
overwrite: True
create_path: True
data_input:
  - datasource: unpd
    root_path: data_regionalization_raw
    variable: total_birth
    download_via: api
    data_file: 
      - tbirths_fact.json
    concordance: unpd_regions_to_5_un_regions.csv 
  - datasource: unpd
    root_path: data_regionalization_raw
    variable: birth_fraction
    download_via: api
    data_file: 
      - tbirths_fact.csv
    concordance: unpd_regions_to_5_un_regions.csv 
    # dependency: True
    # dependency_datasource: unpd
    # dependency_module: birth_rate
    # dependency_file: 
    #   - tbirths_fact.csv
data_output:
  root_path: data_regionalization_clean
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World
  gender:
    - female
    - male



