version: nov2023
module: mortality
overwrite: True
create_path: True
data_input:
  - datasource: wittgenstein
    root_path: data_regionalization_raw
    variable: mortality
    data_file: 
      - mortality_unpopulation_dataportal_20231213103529.csv
    concordance: wittgenstein_regions_to_5_un_regions.csv
  - datasource: unpd
    root_path: data_regionalization_raw
    variable: mortality
    download_via: api
    data_file: 
      - mx5_fact.csv
    concordance: unpd_regions_to_5_un_regions.csv
    dependency: True
    dependency_module: population
    dependency_file: 
      - popbyage5andsex_fact.csv
data_output:
  root_path: data_regionalization_clean
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World
  gender:
    - female
    - male
  age:
    - 0--4
    - 5--9
    - 10--14
    - 15--19
    - 20--24
    - 25--29
    - 30--34
    - 35--39
    - 40--44
    - 45--49
    - 50--54
    - 55--59
    - 60--64
    - 65--69
    - 70--74
    - 75--79
    - 80--84
    - 85--89
    - 90--94
    - 95--99
    - 100+




