version: nov2023
module: energy
overwrite: True
create_path: True
data_input:
  - datasource: world_bank
    root_path: data_regionalization_raw
    variable: elect_loss_rate
    download_via: api
    data_file: 
      - EG_ELC_LOSS_ZS_fact.json
    concordance: world_bank_countries_to_5_un_regions.csv
    dependency: True
    dependency_datasource: world_bank
    dependency_module: energy
    dependency_file: 
      - 4_1_1_TOTAL_ELECTRICITY_OUTPUT_fact.json
  - datasource: iea
    root_path: data_regionalization_raw
    variable: tfc_int_ind
    download_via: manually
    data_file: 
    concordance: 
    dependency: True
    dependency_datasource: world_bank
    dependency_module: gdp
    dependency_file: 
      - NV_IND_TOTL_KD_fact.json
    dependency_concordance: iea_tfc_countries_to_world_bank_countries.csv
data_output:
  root_path: data_regionalization_clean
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World




