version: nov2023
module: population
overwrite: True
create_path: True
data_input:
  - datasource: wittgenstein
    root_path: data_regionalization_raw
    data_file: 
      - wcde_data_1950_2020.csv
    concordance: wittgenstein_regions_to_5_un_regions.csv
  - datasource: world_bank
    root_path: data_regionalization_raw
    data_file: 
      - population_world_bank.csv
    concordance: world_bank_countries_to_5_un_regions.csv
  - datasource: unpd
    root_path: data_regionalization_raw
    download_via: manually
    data_file: 
      - WPP2022_POP_F02_2_POPULATION_5-YEAR_AGE_GROUPS_MALE.xlsx
      - WPP2022_POP_F02_3_POPULATION_5-YEAR_AGE_GROUPS_FEMALE.xlsx
    concordance: unpd_regions_to_5_un_regions.csv
  - datasource: unpd
    root_path: data_regionalization_raw
    download_via: api
    data_file: 
      - popbyage5andsex_fact.csv
    concordance: unpd_regions_to_5_un_regions.csv
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World
  gender:
    - female
    - male
  age:
    - 0--4
    - 5--9
    - 10--14
    - 15--19
    - 20--24
    - 25--29
    - 30--34
    - 35--39
    - 40--44
    - 45--49
    - 50--54
    - 55--59
    - 60--64
    - 65--69
    - 70--74
    - 75--79
    - 80--84
    - 85--89
    - 90--94
    - 95--99
    - 100+



