version: nov2023
module: death_rate
overwrite: True
create_path: True
data_input:
  - datasource: unpd
    root_path: data_regionalization_raw
    variable: total_death
    download_via: api
    data_file: 
      - tdeaths_fact.json
    concordance: unpd_regions_to_5_un_regions.csv 
data_output:
  root_path: data_regionalization_clean
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World
  gender:
    - female
    - male



