version: nov2023
module: labor_force
overwrite: True
create_path: True
data_input:
  - datasource: ilo
    root_path: data_regionalization_raw
    variable: participation_rate
    text: Labour force participation rate by sex and age (%)
    download_via: manually
    data_file: 
      - EAP_DWAP_SEX_AGE_RT_A.csv
    concordance: ilo_countries_to_unpd_regions.csv
    dependency: True
    dependency_module: population
    dependency_datasource: unpd
    dependency_file: 
      - popbyage5andsex_fact.csv
data_output:
  root_path: data_regionalization_clean
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World
  gender:
    - male
    - female
  age:
    - 15-19
    - 20-24
    - 25-29
    - 30-34
    - 35-39
    - 40-44
    - 45-49
    - 50-54
    - 55-59
    - 60-64




