version: nov2023
module: fertility
overwrite: True
create_path: True
data_input:
  - datasource: wittgenstein
    root_path: data_regionalization_raw
    variable: total_fertility
    data_file: 
      - wcde_data_total_fertility_rate_1950_2020.csv
    concordance: wittgenstein_regions_to_5_un_regions.csv
  - datasource: wittgenstein
    root_path: data_regionalization_raw
    variable: age_specific_fertility
    data_file: 
      - XXX.csv
    concordance: wittgenstein_regions_to_5_un_regions.csv
  - datasource: unpd
    root_path: data_regionalization_raw
    variable: total_fertility
    download_via: api
    data_file: 
      - tfr5_fact.json
    concordance: unpd_regions_to_5_un_regions.csv
    dependency: True
    dependency_module: population
    dependency_file: 
      - fempop15_49_fact.csv
  - datasource: unpd
    root_path: data_regionalization_raw
    variable: age_specific_fertility
    download_via: api
    data_file: 
      - asfr5_fact.json
    concordance: unpd_regions_to_5_un_regions.csv
    dependency: True
    dependency_module: population
    dependency_file: 
      - popbyage5andsex_fact.csv
data_output:
  root_path: data_regionalization_clean
dimension:
  region:
    - Africa
    - AsiaPacific
    - EastEu
    - LAC
    - WestEu
    - World
  age:
    - 15--19
    - 20--24
    - 25--29
    - 30--34
    - 35--39
    - 40--44
    - 45--49




